### ISSUE TITLE
query operator 'in' throws "Identifier expects Buffer"

### ISSUE THREAD

**Issue by dashameter** [dashevo/platform#115]
Using an array of buffer identity Ids:

```js
ownerIds :>>  (5) [Uint8Array(32), Uint8Array(32), Uint8Array(32), Uint8Array(32), Uint8Array(32)]
```
And a query using the `in` operator according to https://dashplatform.readme.io/docs/reference-query-syntax#operator-examples

```js
        {
          where: [["$ownerId", "in", ownerIds]],
        }
```

throws:
```
Uncaught (in promise) IdentifierError: Identifier expects Buffer
    at new Identifier (webpack-internal:///./node_modules/@dashevo/dpp/lib/identifier/Identifier.js:18:11)
    at Function.from (webpack-internal:///./node_modules/@dashevo/dpp/lib/identifier/Identifier.js:106:10)
    at convertIdentifierProperties (webpack-internal:///./node_modules/dash/build/src/SDK/Client/Platform/methods/documents/get.js:93:55)
    at eval (webpack-internal:///./node_modules/dash/build/src/SDK/Client/Platform/methods/documents/get.js:130:88)
    at Array.map (<anonymous>)
    at Platform.eval (webpack-internal:///./node_modules/dash/build/src/SDK/Client/Platform/methods/documents/get.js:130:49)
    at step (webpack-internal:///./node_modules/dash/build/src/SDK/Client/Platform/methods/documents/get.js:33:23)
    at Object.eval [as next] (webpack-internal:///./node_modules/dash/build/src/SDK/Client/Platform/methods/documents/get.js:14:53)
    at fulfilled (webpack-internal:///./node_modules/dash/build/src/SDK/Client/Platform/methods/documents/get.js:5:58)
IdentifierError @ IdentifierError.js?93a2:12
Identifier @ Identifier.js?3e2b:18
from @ Identifier.js?3e2b:106
convertIdentifierProperties @ get.js?ae15:93
```

Same happens for an Array of String identityIds.

**Comment by dashameter** [comment]
closed as duplicate of #234
