### ISSUE TITLE
identity topUp throws: "invalid transaction: min relay fee not met"

### ISSUE THREAD

**Issue by dashameter** [dashevo/platform#117]
trying to topUp an identity throws the following error:

```
node topUp.js 
warn: Running on a NodeJS env without any specified adapter. Data will not persist.

Error: 3 INVALID_ARGUMENT: invalid transaction: min relay fee not met, 1000 < 1105 (code 66). Code:-26
    at Object.exports.createStatusError (rates/node_modules/grpc/src/common.js:91:15)
    at Object.onReceiveStatus (rates/node_modules/grpc/src/client_interceptors.js:1209:28)
    at InterceptingListener._callNext (rates/node_modules/grpc/src/client_interceptors.js:568:42)
    at InterceptingListener.onReceiveStatus (rates/node_modules/grpc/src/client_interceptors.js:618:8)
    at InterceptingListener._callNext (rates/node_modules/grpc/src/client_interceptors.js:574:12)
    at InterceptingListener.onReceiveStatus (rates/node_modules/grpc/src/client_interceptors.js:618:8)
    at callback (rates/node_modules/grpc/src/client_interceptors.js:847:24) {
  code: 3,
  metadata: Metadata {
    _internal_repr: {
      server: [ 'nginx/1.19.7' ],
      date: [ 'Thu, 01 Apr 2021 08:27:35 GMT' ],
      'content-length': [ '0' ]
    },
    flags: 0
  },
  details: 'invalid transaction: min relay fee not met, 1000 < 1105 (code 66). Code:-26'
}
```

Tested for topUp amounts from `1e6 to 1e8`

**Comment by dashameter** [comment]
retest failed:

 `InvalidRequestError: Transaction is rejected: min relay fee not met, 0 < 340 (code 66)`

**Comment by dashameter** [comment]
retest passed
