### ISSUE TITLE
Using DashJS (which requires grpc) in AWS Lambda function

### ISSUE THREAD

**Issue by riongull** [dashevo/platform#128]
### Expected Behavior

Expected to be able to use DashJS without issue, regardless of platform.

### Current Behavior

I got a `{"message": "Internal server error"}` when my DashJS-using lambda function fired (which was set up to fire upon an http API request, but that's probably irrelevant).  The original error on AWS showed:

```
{
    "errorType": "Error",
    "errorMessage": "Failed to load gRPC binary module because it was not installed for the current system\nExpected directory: node-v64-linux-x64-glibc\nFound: [node-v64-darwin-x64-unknown]\nThis problem can often be fixed by running \"npm rebuild\" on the current system\nOriginal error: Cannot find module '/var/task/node_modules/grpc/src/node/extension_binary/node-v64-linux-x64-glibc/grpc_node.node'",
    "code": "MODULE_NOT_FOUND",
    "stack": [
        "Error: Failed to load gRPC binary module because it was not installed for the current system",
        "Expected directory: node-v64-linux-x64-glibc",
        "Found: [node-v64-darwin-x64-unknown]",
        "This problem can often be fixed by running \"npm rebuild\" on the current system",
        "Original error: Cannot find module '/var/task/node_modules/grpc/src/node/extension_binary/node-v64-linux-x64-glibc/grpc_node.node'",
        "    at Object.<anonymous> (/var/task/node_modules/grpc/src/grpc_extension.js:53:17)",
        "    at Module._compile (internal/modules/cjs/loader.js:778:30)",
        "    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)",
        "    at Module.load (internal/modules/cjs/loader.js:653:32)",
        "    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)",
        "    at Function.Module._load (internal/modules/cjs/loader.js:585:3)",
        "    at Module.require (internal/modules/cjs/loader.js:692:17)",
        "    at require (internal/modules/cjs/helpers.js:25:18)",
        "    at Object.<anonymous> (/var/task/node_modules/grpc/src/client_interceptors.js:144:12)",
        "    at Module._compile (internal/modules/cjs/loader.js:778:30)"
    ]
}
```

### Problem & Solution

DashJS uses `grpc` under the hood.  The problem seems to be that the `grpc` package you download depends on the platform you run  `npm install` on.  If you are developing on MacOS (`darwin`), the downloaded package will include a directory named `node-v64-darwin-x64-unknown`.  If your function ultimately executes on a different platform than the one you packaged your lambda on there's going to be a problem, because the runtime will look for a folder (e.g. `node-v64-linux-x64-glibc` for the executing platform (typically Linux).

After debugging this for longer than I'd like to admit I figured out the (or at least one possible) solution: 

1. Add the following to your `package.json`:

```
"scripts": {
  "postinstall": "npm rebuild grpc --target_arch=x64 --target_platform=linux --target_libc=glibc"
}
```

I'm pretty sure this *adds* a folder to the package (rather than replacing it), so it should work in both your local and remote environments.  I found this out by first naively trying other solutions like [this](https://stackoverflow.com/questions/47979568/aws-lambda-error-failed-to-load-grpc-binary-module-because-it-was-not-installed/48382484) and [this](https://github.com/grpc/grpc/issues/6138), where they include a specific `--target=x.y.z` in that postinstall script above.  This would add a path to the `"Found: [node-v64-darwin-x64-unknown]"` directory array, but still resulted in an error.  Simply removing the `--target=x.y.z` part did the trick because it seems to default to `process.version`, which should always work.

2. Run `rm -rf ./node_modules/ package-lock.json && npm install` on your development machine.

This removes your cached packages and reinstalls them fresh, now including the target environment's  `grpc` version due to the `postinstall` script.

### Recommendation

I'm not sure if there's anything to do to fix this issue other than to know about how to address it (as explained above), but it might be helpful if there's something that can be changed in the packages DashJS requires for `grpc` so that the issue doesn't arise.

**Comment by dash-maverick** [comment]
@thephez can you refer to that please ?

**Comment by thephez** [comment]
@dash-maverick I was using the library in a different way and the workaround I used isn't applicable for this case. Someone else (probably a dev) will need to look at this. It appears this is still an issue with the latest dev version (0.22-dev.7).

**Comment by thephez** [comment]
@shumkov Some interesting discussion in a GH issue that appears related: https://github.com/npm/cli/issues/2610#issuecomment-914610832. Perhaps updating this would fix it: https://github.com/dashevo/platform/blob/v0.22-dev/packages/dapi-grpc/package.json#L41?

**Comment by shumkov** [comment]
Interesting. @jawid-h @dash-maverick shall we just release your branch as NPM module in dashevo organisation?

**Comment by jawid-h** [comment]
@shumkov yeah, probably we should, let me check if a 7 version is  released

**Comment by jawid-h** [comment]
@shumkov it is not, let's release our version maybe. I would merge latest updates from v6 of the original repo as well

**Comment by dashameter** [comment]
![image](https://user-images.githubusercontent.com/57665975/157864133-796f7891-54c2-4c00-a6d2-a02f340dc05b.png)
retest failed with sdk v3.21.8

**Comment by dash-maverick** [comment]
try it out with  v22 please

**Comment by dashameter** [comment]
retest failed on v22.1

https://runkit.com/622b3b64e1ba8c000a6090da/62403edffa69e900094bb6ee

**Comment by SamKirby22** [comment]
As per triage, unable to reproduce, please retest.

**Comment by dash-maverick** [comment]
Hey. The investigation/fix is being currently in progress. You can expect some updates here quite soon.

**Comment by dashameter** [comment]
retest was requested in discord by @SamKirby22 

with v22.7 it still fails:

![image](https://user-images.githubusercontent.com/57665975/167086886-24968d29-91cb-466e-af9f-6250d3de91c9.png)

**Comment by pshenmic** [comment]
Hey guys. Just checked it out and what I found. :)

The reason why it is not working on RunKit is that they do not pull and update our @dashevo organization NPM packages. If you look up on a search on their website, you will see that `dash` package have recent version, but there isn't even a `@dashevo/platform`, and other `@dashevo` modules are also outdated (since we moved to monorepo).

AWS Lambdas is working fine. Though I needed to bundle Dash SDK in zip first. The reason is that AWS Lambda does not have any internal package manager, so you have to prepare dependencies by yourself. I installed `dash` package in the separate directory and put everything in the .zip file.

https://stackoverflow.com/questions/34437900/how-to-load-npm-modules-in-aws-lambda


After uploading it on my AWS, I have been able to retrieve most recent blockhash via this Lambda code:

```
const Dash = require('dash')

exports.handler = async (event) => {
  const client = new Dash.Client();

  const blockHash = await client.getDAPIClient().core.getBestBlockHash();

  await client.disconnect()

  const response = {
    statusCode: 200,
    body: JSON.stringify('The hash: ' + blockHash),
  };

  return response;
}
```

![image](https://user-images.githubusercontent.com/17009187/168823614-301e2466-1c88-4397-8075-4d0478c51f6a.png)

**Comment by shumkov** [comment]
@thephez shall we update documentation. Maybe we need something like "troubleshooting" section there?

**Comment by dashameter** [comment]
> 

If we can downgrade so it runs on Runkit that would be a good idea.

**Comment by dashameter** [comment]
I retested it on codepen with this snippet:

```
<html>
  <head>
    <title>Load NPM package in browser</title>
    <script
      crossorigin src='https://unpkg.com/dash@3.22.12/dist/dash.min.js'
    ></script>
  </head>

  <body>
    <script>
   async function main () {
   console.log('main')
   const client = new Dash.Client();
   console.log('client')
   
   const blockHash = await client.getDAPIClient().core.getBestBlockHash();
   console.log("blockhash")
   console.log(blockHash)

   const response = {
    statusCode: 200,
    body: JSON.stringify('The hash: ' + blockHash),
  };
   await client.disconnect()

   return response;
}
main()
    </script>
  </body>
</html>
```

and get a network error. This bug describes as expected behavior: Expected to be able to use DashJS without issue, regardless of platform.

So I like to keep this bug open until Dash can be confidently used on a variety of platforms without hiccup.

**Comment by SamKirby22** [comment]
@riongull can you take a quick look at the fix for this and let us know if it's fixed (for your specific use case)?

**Comment by thepastaclaw** [comment]
Closing — the JS SDK has been completely rewritten since this was filed. The old gRPC native binary dependency that caused Lambda compatibility issues is no longer relevant; the SDK now uses `@dashevo/dapi-grpc` with pure JS protobuf bindings. If you still encounter issues using the SDK in serverless environments, please open a new issue with current version details.
