### ISSUE TITLE
`CreateTransactionError: Error: utxosList must contain at least 1 utxo`

### ISSUE THREAD

**Issue by cloudwheels** [dashevo/platform#134]
Current Behavior
This error occurs when attempting to spend funds. It appears the account is undefined. However, the code has also executed correctly, so the problem is intermittent.
The code being executed is here:
https://github.com/dashmachine/autofaucet-express/blob/master/index.js

## Your Environment

Evonet 0.16

I am not sure if this is just dashevo/wallet-lib#178 under a different guise??

Error output:
```
Something went wrong: TypeError: Cannot read property 'getUnusedAddress' of undefined
    at getDrip (/home/nigel/autofaucet-express/index.js:32:33)
    at /home/nigel/autofaucet-express/index.js:83:15
    at Layer.handle [as handle_request] (/home/nigel/autofaucet-express/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/nigel/autofaucet-express/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/home/nigel/autofaucet-express/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/nigel/autofaucet-express/node_modules/express/lib/router/layer.js:95:5)
    at /home/nigel/autofaucet-express/node_modules/express/lib/router/index.js:281:22
    at param (/home/nigel/autofaucet-express/node_modules/express/lib/router/index.js:354:14)
    at param (/home/nigel/autofaucet-express/node_modules/express/lib/router/index.js:365:14)
    at Function.process_params (/home/nigel/autofaucet-express/node_modules/express/lib/router/index.js:410:3)
```

**Comment by dash-maverick** [comment]
Gentlemen, we suggest to close that one and continue in https://github.com/dashevo/platform/issues/136 fyi @dashameter @SamKirby22 @Alex-Werner @markin-io

**Comment by dashameter** [comment]
retest passed, closed

**Comment by dash-maverick** [comment]
so close please :)

**Comment by thephez** [comment]
> so close please :)

Dashameter is probably unable to since someone else opened it :slightly_smiling_face:

**Comment by dash-maverick** [comment]
sorry, my mistake, thanks
