### ISSUE TITLE
Running Platform-test-suite against the testnet network fails on timeout

### ISSUE THREAD

**Issue by mayoreee** [dashevo/platform#218]
I tried running platform-test-suite against the testnet network, and provided the Faucet Private Key for a HD Wallet shown below:

Private key to fund wallets used in tests
`FAUCET_PRIVATE_KEY=cQEutTvyhFdKRfygtTivWKEq8fA84ygWLWy77dBxqrqBwa5fd1oy`

However, the execution remained stuck for a long time, and all tests in the suite failed after the timeout limit was reached.

## Expected Behavior
Successfully execute all tests

## Current Behavior
All tests fail after the timeout limit is reached 

## Steps to Reproduce (for bugs)
`npm run tests`

**Comment by markin-io** [comment]
A relevant error from DAPI:
```
2022-01-26T08:22:11.2925594Z Error: number too large to retain precision - use readVarintBN
2022-01-26T08:22:11.2926543Z     at BufferReader.readVarintNum (/platform/.yarn/cache/@dashevo-dashcore-lib-npm-0.19.29-7b3c802f72-34c9cdf161.zip/node_modules/@dashevo/dashcore-lib/lib/encoding/bufferreader.js:182:15)
2022-01-26T08:22:11.2927681Z     at Function._fromBufferReaderV18 (/platform/.yarn/cache/@dashevo-dashcore-lib-npm-0.19.29-7b3c802f72-34c9cdf161.zip/node_modules/@dashevo/dashcore-lib/lib/instantlock/instantlock.js:115:28)
2022-01-26T08:22:11.2928846Z     at Function._fromBufferReader (/platform/.yarn/cache/@dashevo-dashcore-lib-npm-0.19.29-7b3c802f72-34c9cdf161.zip/node_modules/@dashevo/dashcore-lib/lib/instantlock/instantlock.js:137:28)
2022-01-26T08:22:11.2930111Z     at Function._from (/platform/.yarn/cache/@dashevo-dashcore-lib-npm-0.19.29-7b3c802f72-34c9cdf161.zip/node_modules/@dashevo/dashcore-lib/lib/instantlock/instantlock.js:56:26)
2022-01-26T08:22:11.2931184Z     at new InstantLock (/platform/.yarn/cache/@dashevo-dashcore-lib-npm-0.19.29-7b3c802f72-34c9cdf161.zip/node_modules/@dashevo/dashcore-lib/lib/instantlock/instantlock.js:32:30)
2022-01-26T08:22:11.2932608Z     at ZmqClient.emitInstantLockToFilterCollection (/platform/packages/dapi/lib/transactionsFilter/emitInstantLockToFilterCollectionFactory.js:19:25)
2022-01-26T08:22:11.2934641Z     at ZmqClient.emit (node:events:390:28)
2022-01-26T08:22:11.2935015Z     at exports.Socket.emit (node:events:390:28)
2022-01-26T08:22:11.2935799Z     at exports.Socket.Socket._emitMessage (/platform/.yarn/unplugged/zeromq-npm-5.2.0-1903e18ac9/node_modules/zeromq/lib/index.js:649:15)
2022-01-26T08:22:11.2936624Z     at exports.Socket.Socket._flushRead (/platform/.yarn/unplugged/zeromq-npm-5.2.0-1903e18ac9/node_modules/zeromq/lib/index.js:660:10)
2022-01-26T08:22:11.2937230Z Emitted 'error' event on  instance at:
2022-01-26T08:22:11.2937987Z     at exports.Socket.Socket._flushRead (/platform/.yarn/unplugged/zeromq-npm-5.2.0-1903e18ac9/node_modules/zeromq/lib/index.js:662:10)
2022-01-26T08:22:11.2938982Z     at exports.Socket.Socket._flushReads (/platform/.yarn/unplugged/zeromq-npm-5.2.0-1903e18ac9/node_modules/zeromq/lib/index.js:696:15)
2022-01-26T08:22:11.2939800Z     at Immediate.<anonymous> (/platform/.yarn/unplugged/zeromq-npm-5.2.0-1903e18ac9/node_modules/zeromq/lib/index.js:307:12)
2022-01-26T08:22:11.2940317Z     at processImmediate (node:internal/timers:464:21)
2022-01-26T08:22:11.2940709Z Dashcore ZMQ connection delay
2022-01-26T08:22:11.2941064Z Dashcore ZMQ connection delay
2022-01-26T08:22:11.2941371Z node:events:368
2022-01-26T08:22:11.2941809Z       throw er; // Unhandled 'error' event

```

**Comment by dash-maverick** [comment]
definitely needs a retest

**Comment by SamKirby22** [comment]
@mayoreee please retest.

**Comment by mayoreee** [comment]
retest passed.
