### ISSUE TITLE
dapi-client subscribeToTransactionsWithProofs throws Error: 13 INTERNAL: Received RST_STREAM with code 1

### ISSUE THREAD

**Issue by mayoreee** [dashevo/platform#243]
Attempt to subscribe to transaction information stream in `dapi-client` throws an `Unhandled error event` — “Error: 13 INTERNAL: Received RST_STREAM with code 1”

## Expected Behavior
Successfully subscribe to transaction information stream and return valid data

## Current Behavior
throws an `Unhandled error event`

```
node:events:498
      throw er; // Unhandled 'error' event
      ^

Error: 13 INTERNAL: Received RST_STREAM with code 1
    at Object.callErrorFromStatus (/Volumes/harddrive/Projects/platform_issue_137/node_modules/@grpc/grpc-js/build/src/call.js:31:26)
    at Object.onReceiveStatus (/Volumes/harddrive/Projects/platform_issue_137/node_modules/@grpc/grpc-js/build/src/client.js:331:49)
    at /Volumes/harddrive/Projects/platform_issue_137/node_modules/@grpc/grpc-js/build/src/call-stream.js:111:35
    at Object.onReceiveStatus (/Volumes/harddrive/Projects/platform_issue_137/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:107:9)
    at InterceptingListenerImpl.onReceiveStatus (/Volumes/harddrive/Projects/platform_issue_137/node_modules/@grpc/grpc-js/build/src/call-stream.js:106:23)
    at Object.onReceiveStatus (/Volumes/harddrive/Projects/platform_issue_137/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:328:181)
    at /Volumes/harddrive/Projects/platform_issue_137/node_modules/@grpc/grpc-js/build/src/call-stream.js:182:78
    at processTicksAndRejections (node:internal/process/task_queues:78:11)
Emitted 'error' event on ClientReadableStreamImpl instance at:
    at Object.onReceiveStatus (/Volumes/harddrive/Projects/platform_issue_137/node_modules/@grpc/grpc-js/build/src/client.js:331:28)
    at /Volumes/harddrive/Projects/platform_issue_137/node_modules/@grpc/grpc-js/build/src/call-stream.js:111:35
    [... lines matching original stack trace ...]
    at processTicksAndRejections (node:internal/process/task_queues:78:11) {
  code: 13,
  details: 'Received RST_STREAM with code 1',
  metadata: Metadata { internalRepr: Map(0) {}, options: {} }
}
```

## Steps to Reproduce (for bugs)
```js
var client = new DAPIClient({
        seeds: [{
            host: 'seed-1.testnet.networks.dash.org',
            httpPort: 3000,
            grpcPort: 3010,
        }],
    });

const bloomFilter = {
        "nHashFuncs": 11,
        "vData": "",
        "nTweak": 0,
        "nFlags": 0
    };

const response = await client.core.subscribeToTransactionsWithProofs(bloomFilter, { "fromBlockHeight": 50000 });
```

## Your Environment
* @dashevo/dapi-client@0.21.7

**Comment by dash-maverick** [comment]
to be retested with v0.22

**Comment by mayoreee** [comment]
retest passed in v0.22.1
