### ISSUE TITLE
data contract broadcast error

### ISSUE THREAD

**Issue by mayoreee** [dashevo/platform#324]
Several attempts to broadcast a validated data contract throws `TimeoutError: Deadline exceeded`
## Expected Behavior

Successfully broadcast a validated data contract
## Current Behavior

```
Validation passed, broadcasting contract..
Something went wrong:
 TimeoutError: Deadline exceeded
    at GrpcTransport.createGrpcTransportError (/Volumes/harddrive/Projects/sandbox/node_modules/@dashevo/dapi-client/lib/transport/GrpcTransport/createGrpcTransportError.js:87:12)
    at GrpcTransport.request (/Volumes/harddrive/Projects/sandbox/node_modules/@dashevo/dapi-client/lib/transport/GrpcTransport/GrpcTransport.js:86:34)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async PlatformMethodsFacade.waitForStateTransitionResult (/Volumes/harddrive/Projects/sandbox/node_modules/@dashevo/dapi-client/lib/methods/platform/waitForStateTransitionResult/waitForStateTransitionResultFactory.js:45:54) {
  code: 4,
  data: {},
  dapiAddress: DAPIAddress {
    host: '54.191.227.118',
    httpPort: 3000,
    grpcPort: 3010,
    proRegTxHash: 'a77bea5fc74fc6b3baa6e83884965090ba801a5f0b0998a6441469c9ea135d89',
    banCount: 0,
    banStartTime: undefined
  }
}
```

## Steps to Reproduce (for bugs)

```js
if (validationResult.isValid()) {
    console.log('Validation passed, broadcasting contract..');
    // Sign and submit the data contract
    return platform.contracts.publish(contract, identity);
  }
```

## Your Environment

* Version used: `dash v3.22.1`

**Comment by thephez** [comment]
There is currently an issue with platform on testnet. This is probably related. https://dash-testnet.freshstatus.io/

**Comment by mayoreee** [comment]
retest passed
