### ISSUE TITLE
Retreiving an existing Identity throws  Error: Non-base58 character

### ISSUE THREAD

**Issue by mayoreee** [dashevo/platform#326]
Retreiving an existing Identity throws  `Error: Non-base58 character`
## Expected Behavior

Successfully retrieve existing Identity
## Current Behavior

```
Something went wrong:
 Error: Non-base58 character
    at Object.decode (/Volumes/harddrive/Projects/sandbox/node_modules/@dashevo/dpp/node_modules/base-x/src/index.js:111:11)
    at Function.from (/Volumes/harddrive/Projects/sandbox/node_modules/@dashevo/dpp/lib/identifier/Identifier.js:94:21)
    at Platform.<anonymous> (/Volumes/harddrive/Projects/sandbox/node_modules/dash/build/src/SDK/Client/Platform/methods/identities/get.js:62:55)
    at step (/Volumes/harddrive/Projects/sandbox/node_modules/dash/build/src/SDK/Client/Platform/methods/identities/get.js:33:23)
    at Object.next (/Volumes/harddrive/Projects/sandbox/node_modules/dash/build/src/SDK/Client/Platform/methods/identities/get.js:14:53)
    at fulfilled (/Volumes/harddrive/Projects/sandbox/node_modules/dash/build/src/SDK/Client/Platform/methods/identities/get.js:5:58)
```

## Steps to Reproduce (for bugs)

```js
const Dash = require('dash');

const client = new Dash.Client();

const retrieveIdentity = async () => {
  return client.platform.identities.get('an identity ID goes here');
};

retrieveIdentity()
  .then((d) => console.log('Identity retrieved:\n', d.toJSON()))
  .catch((e) => console.error('Something went wrong:\n', e))
  .finally(() => client.disconnect());
```

## Your Environment

* Version used: `dash v3.22.1

**Comment by mayoreee** [comment]
retest passed
