### ISSUE TITLE
Top-up balance of an existing Identity throws error

### ISSUE THREAD

**Issue by mayoreee** [dashevo/platform#327]
Top-up balance of an existing Identity throws  `StateTransitionBroadcastError: Invalid instant lock proof signature`
## Expected Behavior

Successfully top-up balance of an existing Identity
## Current Behavior

```
Something went wrong:
 [StateTransitionBroadcastError: Invalid instant lock proof signature] {
  code: 1042,
  cause: InvalidInstantAssetLockProofSignatureError: Invalid instant lock proof signature
      at createConsensusError (/Volumes/harddrive/Projects/sandbox/node_modules/@dashevo/dpp/lib/errors/consensus/createConsensusError.js:14:10)
      at GrpcTransport.createGrpcTransportError (/Volumes/harddrive/Projects/sandbox/node_modules/@dashevo/dapi-client/lib/transport/GrpcTransport/createGrpcTransportError.js:132:28)
      at GrpcTransport.request (/Volumes/harddrive/Projects/sandbox/node_modules/@dashevo/dapi-client/lib/transport/GrpcTransport/GrpcTransport.js:86:34)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async PlatformMethodsFacade.broadcastStateTransition (/Volumes/harddrive/Projects/sandbox/node_modules/@dashevo/dapi-client/lib/methods/platform/broadcastStateTransition/broadcastStateTransitionFactory.js:33:50) {
    [Symbol(constructorArguments)]: []
  }
}

```

## Steps to Reproduce (for bugs)

```js
const Dash = require('dash');

const clientOpts = {
  network: 'testnet',
  wallet: {
    mnemonic: 'a Dash wallet mnemonic with testnet funds goes here',
    unsafeOptions: {
      skipSynchronizationBeforeHeight: 650000, // only sync from early-2022
    },
  },
};
const client = new Dash.Client(clientOpts);

const topupIdentity = async () => {
  const identityId = 'an identity ID goes here';
  const topUpAmount = 1000; // Number of duffs

  await client.platform.identities.topUp(identityId, topUpAmount);
  return client.platform.identities.get(identityId);
};

topupIdentity()
  .then((d) => console.log('Identity credit balance: ', d.balance))
  .catch((e) => console.error('Something went wrong:\n', e))
  .finally(() => client.disconnect());
```

## Your Environment

* Version used: `dash v3.22.1

**Comment by mayoreee** [comment]
retest passed
