### ISSUE TITLE
error: Error syncing incoming transactions offset is not uint [RangeError: offset is not uint]

### ISSUE THREAD

**Issue by dashameter** [dashevo/platform#395]
I'm getting 

```
error: Error syncing incoming transactions offset is not uint [RangeError: offset is not uint]
```

```
index.js?b639:1097 Uncaught (in promise) RangeError: offset is not uint
    at checkOffset (index.js?b639:1097:1)
    at Uint8Array.readUInt32BE (index.js?b639:1157:1)
    at eval (sortTransactions.js?670d:35:1)
    at Array.forEach (<anonymous>)
    at eval (sortTransactions.js?670d:34:1)
    at Array.sort (<anonymous>)
    at eval (sortTransactions.js?670d:31:1)
    at Array.reduce (<anonymous>)
    at sortTransactions (sortTransactions.js?670d:30:1)
    at ChainStore.importAddress (importAddress.js?2682:27:1)
```

```
/*
 * Need to make sure that buffer isn't trying to write out of bounds.
 */
function checkOffset (offset, ext, length) {
  if ((offset % 1) !== 0 || offset < 0) throw new RangeError('offset is not uint')
  if (offset + ext > length) throw new RangeError('Trying to access beyond buffer length')
}
```

```diff
return Object.keys(transactionsByHeight)
    .sort((a, b) => parseInt(a, 10) - parseInt(b, 10))
    .reduce((acc, height) => {
      transactionsByHeight[height].sort((a, b) => {
        // const prevTxHashBuffer = Buffer.alloc(32);
        const prevTxHashes = new Set();
        b.inputs.forEach((input) => {
+          if (input.prevTxId.readUInt32BE() !== 0) {
            prevTxHashes.add(input.prevTxId.toString('hex'));
          }
        });

        if (prevTxHashes.has(a.hash)) {
          return -1;
        }
        return 0;
      });
      return acc.concat(transactionsByHeight[height]);
    }, []);
```

using dashmate 22.7

This seems to be related to webpack5

**Comment by mayoreee** [comment]
Workaround 1: For using `Dash SDK` with `Webpack`


1. Change the content of `vue.config.js` to:
```
module.exports = {
  configureWebpack: {
    resolve: {
      alias: {
        zlib: require.resolve('browserify-zlib'),
        http: require.resolve('stream-http'),
        https: require.resolve('https-browserify'),
        os: require.resolve('os-browserify/browser'),
        path: require.resolve('path-browserify'),
        fs: require.resolve('fs'),
        util: require.resolve('util'),
        stream: require.resolve('stream-browserify'),
        assert: require.resolve('assert'),
        crypto: require.resolve('crypto-browserify'),
        url: require.resolve('url'),
      },
    },
  },
};
```
2. Run these commands:
```
npm i browserify-zlib
npm i stream-http
npm i https-browserify
npm i os-browserify
npm i path-browserify
npm i fs
npm i util
npm i stream-browserify
npm i assert
npm i crypto-browserify
npm i url
```

3. `npm run serve`

**Comment by mayoreee** [comment]
Workaround 2: For using `Dash SDK` with `Vite`

So, I got `dash sdk` working with `Vite` with these steps:

1. Change the content of `vue.config.js` to:
```
import { fileURLToPath, URL } from 'url'

import { defineConfig } from 'vite'
import vue from '@vitejs/plugin-vue'

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [vue()],
  resolve: {
    alias: {
      zlib: require.resolve('browserify-zlib'),
      http: require.resolve('stream-http'),
      https: require.resolve('https-browserify'),
      os: require.resolve('os-browserify/browser'),
      path: require.resolve('path-browserify'),
      fs: require.resolve('fs'),
      util: require.resolve('util'),
      stream: require.resolve('stream-browserify'),
      assert: require.resolve('assert'),
      crypto: require.resolve('crypto-browserify'),
      url: require.resolve('url'),
    },
  },
})

```
2. Run these commands:
```
npm i browserify-zlib
npm i stream-http
npm i https-browserify
npm i os-browserify
npm i path-browserify
npm i fs
npm i util
npm i stream-browserify
npm i assert
npm i crypto-browserify
npm i url
```

3. `npm run dev`

**Comment by markin-io** [comment]
You can also refer to the weback config we are using to bundle SDK for karma tests https://github.com/dashevo/platform/blob/v0.23-dev/packages/platform-test-suite/karma.conf.js#L34

**Comment by dashameter** [comment]
I'm getting the error:

```
error: Error syncing incoming transactions offset is not uint [RangeError: offset is not uint]
index.js:1097 Uncaught (in promise) RangeError: offset is not uint
    at X (index.js:1097:47)
    at Uint8Array.E.readUInt32BE (index.js:1157:18)
    at sortTransactions.js:35:30
    at Array.forEach (<anonymous>)
    at sortTransactions.js:34:18
    at Array.sort (<anonymous>)
    at sortTransactions.js:31:36
    at Array.reduce (<anonymous>)
    at e (sortTransactions.js:30:6)
    at o.n [as importAddress] (importAddress.js:27:32)
X @ index.js:1097
E.readUInt32BE @ index.js:1157
(anonymous) @ sortTransactions.js:35
(anonymous) @ sortTransactions.js:34
(anonymous) @ sortTransactions.js:31
e @ sortTransactions.js:30
n @ importAddress.js:27
(anonymous) @ addPathsToStore.js:16
e @ addPathsToStore.js:13
(anonymous) @ importTransactions.js:37
A.exports @ importTransactions.js:20
s @ processChunks.js:37
(anonymous) @ onStreamData.js:7
processJob @ Queue.js:41
processNext @ Queue.js:35
t @ Queue.js:52
I @ events.js:243
s.emit @ events.js:153
enqueueJob @ Queue.js:23
n @ onStreamData.js:7
(anonymous) @ syncUpToTheGapLimit.js:55
(anonymous) @ index.js:49
qA @ index.js:34
zA @ index.js:33
Mt @ index.js:41
pt.O @ index.js:40
pt.K @ index.js:40
VM383:1          POST http://54.187.50.120:3000/org.dash.platform.dapi.v0.Core/subscribeToTransactionsWithProofs 504 (Gateway Time-out)
(anonymous) @ VM383:1
Rt @ index.js:38
Ae @ index.js:59
(anonymous) @ index.js:55
$t.R @ index.js:55
i.org.dash.platform.dapi.v0.CorePromiseClient.subscribeToTransactionsWithProofs @ core_grpc_web_pb.js:619
request @ GrpcTransport.js:71
await in request (async)
e @ subscribeToTransactionsWithProofsFactory.js:74
A.exports @ subscribeToTransactionsWithProofs.js:47
A.exports @ syncUpToTheGapLimit.js:35
A @ startIncomingSync.js:22
await in A (async)
execute @ TransactionSyncStreamWorker.js:182
execWorker @ Worker.js:119
startWorker @ Worker.js:70
await in startWorker (async)
(anonymous) @ injectPlugin.js:100
A.exports @ injectPlugin.js:24
(anonymous) @ _preparePlugins.js:9
Promise.then (async)
e @ _preparePlugins.js:7
(anonymous) @ _preparePlugins.js:29
n @ _preparePlugins.js:25
(anonymous) @ _initializeAccount.js:22
a @ _initializeAccount.js:19
init @ Account.js:213
await in init (async)
n @ createAccount.js:32
a @ getAccount.js:30
await in a (async)
(anonymous) @ index.js:504
_ @ runtime.js:63
(anonymous) @ runtime.js:293
(anonymous) @ runtime.js:118
r @ asyncToGenerator.js:3
o @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
initWallet @ index.js:456
(anonymous) @ vuex.esm.js:851
f.dispatch @ vuex.esm.js:516
dispatch @ vuex.esm.js:406
resetState @ index.js:127
(anonymous) @ vuex.esm.js:844
(anonymous) @ vuex.esm.js:466
(anonymous) @ vuex.esm.js:465
f._withCommit @ vuex.esm.js:624
f.commit @ vuex.esm.js:464
commit @ vuex.esm.js:409
(anonymous) @ Wallet.vue:361
_ @ runtime.js:63
(anonymous) @ runtime.js:293
(anonymous) @ runtime.js:118
r @ asyncToGenerator.js:3
o @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
forgetState @ Wallet.vue:359
et @ vue.runtime.esm.js:1854
e @ vue.runtime.esm.js:2179
et @ vue.runtime.esm.js:1854
Re.A.$emit @ vue.runtime.esm.js:3888
click @ VBtn.ts:159
et @ vue.runtime.esm.js:1854
e @ vue.runtime.esm.js:2179
n._wrapper @ vue.runtime.esm.js:6917
Show 31 more frames
VM383:1          POST http://34.215.144.176:3000/org.dash.platform.dapi.v0.Core/subscribeToTransactionsWithProofs 504 (Gateway Time-out)
(anonymous) @ VM383:1
Rt @ index.js:38
Ae @ index.js:59
(anonymous) @ index.js:55
$t.R @ index.js:55
i.org.dash.platform.dapi.v0.CorePromiseClient.subscribeToTransactionsWithProofs @ core_grpc_web_pb.js:619
request @ GrpcTransport.js:71
await in request (async)
e @ subscribeToTransactionsWithProofsFactory.js:74
A.exports @ subscribeToTransactionsWithProofs.js:47
A.exports @ syncUpToTheGapLimit.js:35
A @ startIncomingSync.js:22
await in A (async)
execute @ TransactionSyncStreamWorker.js:182
execWorker @ Worker.js:119
startWorker @ Worker.js:70
await in startWorker (async)
(anonymous) @ injectPlugin.js:100
A.exports @ injectPlugin.js:24
(anonymous) @ _preparePlugins.js:9
Promise.then (async)
e @ _preparePlugins.js:7
(anonymous) @ _preparePlugins.js:29
n @ _preparePlugins.js:25
(anonymous) @ _initializeAccount.js:22
a @ _initializeAccount.js:19
init @ Account.js:213
await in init (async)
n @ createAccount.js:32
a @ getAccount.js:30
await in a (async)
(anonymous) @ index.js:504
_ @ runtime.js:63
(anonymous) @ runtime.js:293
(anonymous) @ runtime.js:118
r @ asyncToGenerator.js:3
o @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
initWallet @ index.js:456
(anonymous) @ vuex.esm.js:851
f.dispatch @ vuex.esm.js:516
dispatch @ vuex.esm.js:406
resetState @ index.js:127
(anonymous) @ vuex.esm.js:844
(anonymous) @ vuex.esm.js:466
(anonymous) @ vuex.esm.js:465
f._withCommit @ vuex.esm.js:624
f.commit @ vuex.esm.js:464
commit @ vuex.esm.js:409
(anonymous) @ Wallet.vue:399
_ @ runtime.js:63
(anonymous) @ runtime.js:293
(anonymous) @ runtime.js:118
r @ asyncToGenerator.js:3
o @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
Promise.then (async)
(anonymous) @ Wallet.vue:398
_ @ runtime.js:63
(anonymous) @ runtime.js:293
(anonymous) @ runtime.js:118
r @ asyncToGenerator.js:3
o @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
createMnemonic @ Wallet.vue:395
click @ Wallet.vue?383d:1
et @ vue.runtime.esm.js:1854
e @ vue.runtime.esm.js:2179
et @ vue.runtime.esm.js:1854
Re.A.$emit @ vue.runtime.esm.js:3888
click @ VBtn.ts:159
et @ vue.runtime.esm.js:1854
e @ vue.runtime.esm.js:2179
n._wrapper @ vue.runtime.esm.js:6917
VM383:1          POST http://34.211.49.3:3000/org.dash.platform.dapi.v0.Core/subscribeToTransactionsWithProofs net::ERR_INCOMPLETE_CHUNKED_ENCODING 200 (OK)
(anonymous) @ VM383:1
Rt @ index.js:38
Ae @ index.js:59
(anonymous) @ index.js:55
$t.R @ index.js:55
i.org.dash.platform.dapi.v0.CorePromiseClient.subscribeToTransactionsWithProofs @ core_grpc_web_pb.js:619
request @ GrpcTransport.js:71
await in request (async)
e @ subscribeToTransactionsWithProofsFactory.js:74
A.exports @ subscribeToTransactionsWithProofs.js:47
A.exports @ syncUpToTheGapLimit.js:35
A @ startIncomingSync.js:22
await in A (async)
A @ startIncomingSync.js:38
await in A (async)
execute @ TransactionSyncStreamWorker.js:182
execWorker @ Worker.js:119
startWorker @ Worker.js:70
await in startWorker (async)
(anonymous) @ injectPlugin.js:100
A.exports @ injectPlugin.js:24
(anonymous) @ _preparePlugins.js:9
Promise.then (async)
e @ _preparePlugins.js:7
(anonymous) @ _preparePlugins.js:29
n @ _preparePlugins.js:25
(anonymous) @ _initializeAccount.js:22
a @ _initializeAccount.js:19
init @ Account.js:213
await in init (async)
n @ createAccount.js:32
a @ getAccount.js:30
await in a (async)
(anonymous) @ index.js:504
_ @ runtime.js:63
(anonymous) @ runtime.js:293
(anonymous) @ runtime.js:118
r @ asyncToGenerator.js:3
o @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
initWallet @ index.js:456
(anonymous) @ vuex.esm.js:851
f.dispatch @ vuex.esm.js:516
dispatch @ vuex.esm.js:406
(anonymous) @ Wallet.vue:401
_ @ runtime.js:63
(anonymous) @ runtime.js:293
(anonymous) @ runtime.js:118
r @ asyncToGenerator.js:3
o @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
Promise.then (async)
(anonymous) @ Wallet.vue:398
_ @ runtime.js:63
(anonymous) @ runtime.js:293
(anonymous) @ runtime.js:118
r @ asyncToGenerator.js:3
o @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
createMnemonic @ Wallet.vue:395
click @ Wallet.vue?383d:1
et @ vue.runtime.esm.js:1854
e @ vue.runtime.esm.js:2179
et @ vue.runtime.esm.js:1854
Re.A.$emit @ vue.runtime.esm.js:3888
click @ VBtn.ts:159
et @ vue.runtime.esm.js:1854
e @ vue.runtime.esm.js:2179
n._wrapper @ vue.runtime.esm.js:6917
VM383:1          POST http://54.148.106.179:3000/org.dash.platform.dapi.v0.Core/subscribeToTransactionsWithProofs 504 (Gateway Time-out)
(anonymous) @ VM383:1
Rt @ index.js:38
Ae @ index.js:59
(anonymous) @ index.js:55
$t.R @ index.js:55
i.org.dash.platform.dapi.v0.CorePromiseClient.subscribeToTransactionsWithProofs @ core_grpc_web_pb.js:619
request @ GrpcTransport.js:71
await in request (async)
e @ subscribeToTransactionsWithProofsFactory.js:74
A.exports @ subscribeToTransactionsWithProofs.js:47
A.exports @ syncUpToTheGapLimit.js:35
A @ startIncomingSync.js:22
await in A (async)
A @ startIncomingSync.js:38
VM383:1          POST http://35.166.29.155:3000/org.dash.platform.dapi.v0.Core/subscribeToTransactionsWithProofs 504 (Gateway Time-out)
```

on testnet during identity creation using webpack 4.

Sometimes I get it with dashmate and webpack 4 but if I refresh the walelt often enough the error goes away and I can use the sdk as expect :thinking:

**Comment by dashameter** [comment]
retest passed dashmate@.22.12
